---
# install
- name: Ensure Apache is installed on RHEL.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ apache_enablerepo }}"
  with_items: "{{ apache_packages }}"
  tags:
    - apache-install
    - apache

# configure
- include: config.yml
  static: no
  tags:
    - apache-config
    - apache

# service
- name: Ensure Apache is started and enabled to start at boot.
  service: name="{{ apache_service }}" state=started enabled=yes
  tags:
    - apache-service
    - apache
