---

- name: Ensure Apache is installed on RHEL.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ apache_enablerepo }}"
  with_items: "{{ apache_packages }}"

- name: Place Apache configuration file in place.
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 00644
  notify: restart apache

# service
- name: Ensure Apache is started and enabled to start at boot.
  service: name=httpd state=started enabled=yes
